### ISSUE TITLE
Hi there dwij

### ISSUE THREAD

**Issue by shortthefomo** [ssd39/xrpl-trust-flow#1]
Saw this project in one of the ripple hack athons, and I really liked the concept you had put forward. I had spoken with Matt Hamilton many times and his always point to using or doing something like "node red" this is the very first thing that jumped to mind when I saw this.

So I have spend some time playing with it my self to understand the possibilities a bit more, and this really has potential to open up wiring transactions together for many non developers.

Anyhow, im reaching out to see if we could possibly work together a bit, I also have ideas for this past simple hosted flows, but rather taking these into smart contracts.

Not Sure how were to contact you to talk further.

Lathan

**Comment by ssd39** [comment]
Hi @lathanbritz ,

I'm glad you find this project interesting. Currently, it is just a demonstration of how we can create an escrow using no code. However, there are many possibilities, such as creating a whole smart contract using no code, creating DeFi automation, or complex transaction flows, and much more. I'm happy to work on these types of project ideas that help non-developer users adopt blockchain. Feel free to contact me on my Telegram: @idorhhhh
